### ISSUE TITLE
Gutenberg 5.0 component display issues

### ISSUE THREAD

**Issue by phpbits** [thatplugincompany/coblocks#250] opened 2019-02-08 05:04 UTC
Buttons doesn't on our controls doesn't look good on 5.0 updates.

<img width="280" alt="screen shot 2019-02-08 at 1 02 17 pm" src="https://user-images.githubusercontent.com/3365507/52459759-ffa14980-2ba1-11e9-8743-0a3caed550c1.png">

**Comment by phpbits** [comment] 2019-02-08 05:06
Same with Typography controls.

<img width="689" alt="screen shot 2019-02-08 at 1 06 03 pm" src="https://user-images.githubusercontent.com/3365507/52459818-527b0100-2ba2-11e9-92e2-d2430930e478.png">

**Comment by onuro** [comment] 2019-02-08 08:41
Hey guys, big fan! Love your work!

Just so you know, latest gutenberg plugin update slightly breaks most of the button and switch related styles. This also happened to my plugin, and metabox, and two more plugins I know in editor view.

I'd say wait for next release of GB until we know for  sure the issue is here to stay :)

Cheers,
Onur

**Comment by phpbits** [comment] 2019-02-08 12:51
@onuro thanks! Really glad that you are loving CoBlocks! We'll find fixes for now which is better that waiting for the next updates I think :)

**Comment by phpbits** [comment] 2019-02-08 12:51
@richtabor Same with Accordion add new item button

<img width="677" alt="screen shot 2019-02-08 at 8 49 53 pm" src="https://user-images.githubusercontent.com/3365507/52479361-524f2580-2be3-11e9-99a7-87a1bfcbcb33.png">

**Comment by richtabor** [comment] 2019-02-08 12:54
Thanks @phpbits, I've opened #251 for the accordion

**Comment by richtabor** [comment] 2019-02-08 13:55
Blocks to review:

- [Icon ]

**Comment by richtabor** [comment] 2019-02-08 14:04
> Same with Typography controls.
> 
> <img alt="screen shot 2019-02-08 at 1 06 03 pm" width="689" src="https://user-images.githubusercontent.com/3365507/52459818-527b0100-2ba2-11e9-92e2-d2430930e478.png">

Fixed this.

**Comment by richtabor** [comment] 2019-02-08 15:42
I think we have them all fixed now.

**Closed by richtabor** 2019-02-08 15:42 UTC
Labels: Bug, UI
